version: '3.7'

services:
  tm-admin-web:
    container_name: tm-admin-web

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - '.:/app'
      - '/app/node_modules'

    ports:
      - '3000:3000'

    environment:
      - NODE_ENV=development
