# build environment
FROM node:10-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

ARG environment=sogaz

COPY package.json /app/package.json
COPY env.example /app/.env.production

RUN npm install react-scripts@3.0.1 -g --silent
RUN npm install --silent

COPY . /app

RUN npm run build

# production environment
FROM nginx:1.16.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
